version: "3.9"
services:
  web:
    image: "blizda/mt5"
    env_file:
      - ./.env
    environment:
      - WB_KEY=${WB_KEY}
    command: >
      bash -c "wandb login ${WB_KEY}
      && git clone https://github.com/blizda/mt5-title-generator.git
      && cd mt5-title-generator/inference/
      && gunicorn -t 210 -b :8080 infer_model:app"
    ports:
      - "8080:8080"